spring:
  application:
      name: client-feign

server:
  port: 80

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8000/eureka/

feign: 
  httpclient:
    enable: false
  okhttp:
    enable: true

ribbon:
   eureka:
      enable: true
   eager-load:
      enabled: true
      clients: service-provider,service-provider2
   ConnectTimeout: 5000
   ReadTimeout: 5000

#更改负载策略，本地优先
service-provider:
   ribbon:
      NFLoadBalancerRuleClassName: test.consumer.MyLocalPriorityRule
service-provider2:
   ribbon:
      NFLoadBalancerRuleClassName: test.consumer.MyLocalPriorityRule
serverIP: 192.168.2.126
    
hystrix:
   command:
      default:
         execution:
            thread:
               timeoutInMilliseconds: 5000